version: "2.0"

services:
  flaskserver:
    build: flaskserver
    ports:
      - 5000:5000
    depends_on:
      - redisdb
    environment:
      - ENV_HOST=database
      - ENV_PORT=6379
      - ENV_DB=0
    links:
      - "redisdb:database"

  redisdb:
    image: 'bitnami/redis:latest'
    ports:
      - 6379:6379
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
      
  staticserver:
    image: nginx
    ports:
      - 80:80
  proxy:
    image: nginx
    ports:
      - 8080:80