version: "2.0"
services:
  flaskserver:
    build: flaskserver
    expose:
      - 5000
    depends_on:
      - redisdb
  
  redisdb:
    image: 'bitnami/redis:latest'
    environment:
      - ALLOW_EMPTY_PASSWORD=yes