version: "2.0"
services:
  flaskserver:
    build: flaskserver
    ports:
      - 5000:5000
    depends_on:
      - redisdb

  redisdb:
    image: 'bitnami/redis:latest'
    ports:
      - 81:6379
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
      
  staticserver:
    image: nginx
    ports:
      - 80:80
  proxy:
    image: nginx
    ports:
      - 8080:80